spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-105.railway.app:7952/railway
    username: postgres
    password: GLfdzsIrt5tuBtIWprKy
    name: railway

sql:
  init:
    mode: always
